sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: csb2G5RS2KntXO9S+hmEv/NIExkhCOdejEN3c9RtRbgEV2lpk1nbEDDl9/D0XIAUJ+Ic1kpRk5cALoS2e3t+oY377LNWLKiaQI1QmQokxNr4IjjWJvQ3GLjO12of1aBSk7c22HxhstnShCpKlU3nw7qF3yVIZ89ob3Eqf2G59cb9Xt6BS4VQat1MBxflD9ogZk2hkGVzZ0GZ/0YsIbDpD2jzIF8wS79msOPmBGMs2rRsMMtKE5ENovfdO6KxeZu53bJLbLabRrvWiGoXX7SoR9UK4xedEXUnIC1Rg45qhVXDz8cjTAvbR+nyGIF0AHild1R5npcCl/SXGONlFY9XCuVlnx/uuYDxoQ4LbseaTcsXEPn1YVSy9X3JAY13mi/3e1QcE9UgHswAq9FZ9HEdfBaiNxUFLW1ktabJB1aLJEGE9u7UMUfYhTBbVuCTKRiGTTnVaB3rS96gYNYVCGOW9M87X/ii+JejCvl7vZhXMA1VHSG8DxN2HkO45N6qdqoQOKjRBdSwSV3oA0q66eNwrHdAOzTVv06L7gSTAlKFfDwXK0SKYFlHrVuchrAfp9fPeo9w5Te+dBpVRzA3099VkIn1AlG+XSd1ckQNVYJTFGUKsCH5nJJgN0es+JJJ+yXtiAM6ZDYNgTyROd4X5Q7shwL+WGjGwDAv+oazxrZNpdg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Confessions-of-Jean-Jacques-Rousseau---Volume-04_3904
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy